- name: Create a portainer container
  docker_container:
    name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    image: portainer/portainer-ce:latest
    state: started
    recreate: yes
