- hosts: "*"
  become: yes
  tasks:
    - include_tasks: ../tasks/apt-upgrade.yml
    - include_tasks: ../tasks/docker-setup.yml
    - include_tasks: ../tasks/portainer/create-volume.yml
    - include_tasks: ../tasks/portainer/create-container.yml
